language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t krisnakris/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krisnakris/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "dokcer-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-687852198989"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY